FROM gotchas/pharo-teapot
MAINTAINER Christer Assmundsson

RUN ./pharo Pharo.image config http://www.smalltalkhub.com/mc/Gotchas/Jobb/main ConfigurationOfXmlJson --install=stable

RUN echo "XmlJson installed"
