# gotchas/pharo-seaside
FROM gotchas/pharo-teapot
MAINTAINER Christer Assmundsson

EXPOSE 8080
#RUN ./pharo-run get Seaside3 && rm -fr pharo-local
RUN ./pharo-run get Bootstrap && rm -fr pharo-local
RUN echo "Seaside installed"

